### ISSUE TITLE
Able to walk through some props as both prop and hunter

### ISSUE THREAD

**Issue by Happy97** [mechanicalmind/prophunters#16]
I newly made a server using SteamCMD.

After running around in game a bit, i realized that I, for some reason, could walk through certain props (See Images).

![2015-04-28_00001](https://cloud.githubusercontent.com/assets/6883988/7396451/552b7340-eea1-11e4-8aaa-3cb122a62515.jpg)
![2015-04-28_00002](https://cloud.githubusercontent.com/assets/6883988/7396452/553123c6-eea1-11e4-9204-e10b97464bd7.jpg)
![2015-04-28_00003](https://cloud.githubusercontent.com/assets/6883988/7396453/554563ae-eea1-11e4-82e2-7fd57afd5b9d.jpg)
![2015-04-28_00004](https://cloud.githubusercontent.com/assets/6883988/7396454/554c803a-eea1-11e4-9512-75f0c8338da4.jpg)

Why is this? Can i fix it with a command? Is it a common bug in new servers?

-- Happy --

**Comment by mechanicalmind** [comment]
You need to install CS:S content. The certain props are from CS:S so your server doesn't have a collision mesh for them.
