### ISSUE TITLE
New fixes

### ISSUE THREAD

**Issue by Stinggy** [MechanicalMind/prophunters#27]
I'm just curious I have heavily modified this game mode and I'm trying to figure out what exactly I need to change with the text files any help appreciated. I'm not sure how many files really need changed at this point.

I was trying to figure out how many changes there were from the commits. 

Is this an issue server side or just from the workshop?

**Comment by akersda** [comment]
If you use the gamemode unpacked nothing needs to be changed.
gmod made an update that prevented the use of .txt files in packed addons (.gma files) anywhere but the root gamemode directory (the gamemode had a txt file explaining how to add taunts and a licence file, which was blocking the workshop addon from loading).

**Comment by Stinggy** [comment]
Ok that was what I was wondering and I do use it unpacked. Thank you very much

**Comment by Stinggy** [comment]
Thanks again
