### ISSUE TITLE
Free cam

### ISSUE THREAD

**Issue by Stinggy** [MechanicalMind/prophunters#8]
Just curious how hard it would be to add OBS_MODE_ROAMING for spectators so they could switch from chase or roaming. I think the original version did this using spacebar. I have had this brought up from many users in the game so thought I would ask.

Thanks

**Comment by lewis-conroy** [comment]
Was this ever implemented? I may have an out of date version but I installed via Steam Workshop so I imagine i'm up to date?

**Comment by MechanicalMind** [comment]
Yes, need to enabled the convar ph_dead_canroam if you want to allow it for dead players.

**Comment by lewis-conroy** [comment]
awesome, thanks!
